lua/pl/utils.lua

this is just a quick fix for a typo in the documentation :-)

fixed a typo

---

lua/pl/pretty.lua

Disable debug hooks alongside string metamethods when loading code
in pl.pretty. A debug hook can be called on each line, including
inside sandboxed code, and may require string methods to work correctly.
Also save string metatable as as whole instead of patching __index
metamethod.

Save and restore debug hooks in pl.pretty

---

lua/pl/lexer.lua
tests/test-lexer.lua

Some lexer fixes, see commits. Seems to work nicely, except it breaks on files when there are multi line tokens, and extension using `matches` argument is not documented.

pl.lexer fixes

---

lua/pl/url.lua

Mostly cosmetic changes. Fixed an accidental global, made docs a little more descriptive, fixed formatting.
I'm not sure why the functions return original argument if it's nil or false (`not type(s) == "string"` is always false). Most likely proper typechecking should be added instead.

pl.url fixes

---

lua/pl/sip.lua
tests/test-sip.lua

Fixes space compressing and crash on SIP pattern without actual patterns, plus clean-ups and doc fixes.

pl.sip fixes

---

lua/pl/class.lua
tests/test-class.lua

added some tests, allow to get an instances class through instance:is_a()

---

lua/pl/config.lua
tests/test-config.lua

I made a small change to pl.config to allow automatic conversion of "true" and "false" to boolean values when reading configuration files

Add option to convert booleans in config files

---

lua/pl/pretty.lua
tests/test-pretty.lua

Apply fix suggested by @rvandermate. Fixes #172.

Fix pretty.read failing on 'function' within strings

---

lua/pl/dir.lua

Fixes issue #218 where dir.getallfiles returns nothing if no pattern is specifed

---

CHANGES.md
lua/pl/tablex.lua
tests/test-tablex.lua

tablex.reduce can take an optional initial memo

---

lua/pl/seq.lua
lua/pl/url.lua
tests/test-seq.lua

Redid PR #230 as a separate branch.

---

lua/pl/lapp.lua

lapp: Convert default values using the associated converter function

---

CHANGELOG.md
lua/pl/types.lua
tests/test-types.lua

Bugfixes in
- types.is_empty, where strings containing spaces were not properly evaluated
- types.to_bool, would not properly compare additional truthy values (case sensitive)

Test coverage, 2 bugfixes, and doc updates

---

lua/pl/file.lua

Since this module has outdated docs, the contents is removed and
replaced with references to the original functions as to reduce
documentation maintenance.

update pl.file docs (remove and replace with references)

---

CHANGELOG.md
lua/pl/stringx.lua
tests/test-stringx.lua

fix(stringx) do not append empty string if hit number of matches

---

CHANGELOG.md
lua/pl/stringx.lua
tests/test-stringx.lua

fix(stringx) rpartition returned bad order args if not found

---

tests/test-app.lua

fix(tests) do not require luacov if not specified

---

lua/pl/compat.lua
lua/pl/path.lua
tests/test-compat.lua

fix(compat) Lua 5.1 package.search_path implementation #328

---

.luacov
appveyor.yml

Unfortunately there seems to be an issue that prevents reporting the test results.

Enable Windows coverall stats

---

README.md

Update URLs in sources

---

CHANGELOG.md
docs_topics/05-dates.md
lua/pl/Date.lua

chore(Date) deprecate the Date module/class

---

lua/pl/permute.lua
spec/permute_spec.lua

change is non-breaking since these functions weren't released yet

fix(permute) make order logical

---

appveyor.yml

related issue: https://github.com/moteus/luacov-coveralls/issues/26

chore(ci) remove workaround after LuaRocks fix

---

CHANGELOG.md
lua/pl/xml.lua

fix(xml) xml.maptags hangs on text nodes

---

CHANGELOG.md
lua/pl/dir.lua

Allows for calling dir.getfiles(),  dir.getdirectories(), dir.getallfiles(), with no args

fix(dir) Added default "." for dir and start_path

---

CHANGELOG.md
lua/pl/compat.lua
lua/pl/utils.lua
spec/utils-enum_spec.lua

feat: 'utils.enum' to create enums, and prevent magic strings

---

CHANGELOG.md
lua/pl/path.lua
tests/test-path.lua

fix(path) ensure win paths like "c:\\" are directories

---

lua/pl/compat.lua

See [comment here](https://github.com/lunarmodules/Penlight/pull/437/files#r927495273).

Fixup strict checker fix

---

CHANGELOG.md
lua/pl/template.lua
tests/test-template.lua

fix(template): using magic characters as escapes

---

README.md
rockspecs/penlight-1.14.0-2.rockspec

fix(rockspec): back to LuaRocks 2.x rockspec

---

.github/workflows/unix_build.yml

see https://github.com/luarocks/luarocks/issues/1797

fix(ci): on unix bump luarocks to fix luajit issue
