- lua/pl/path.lua
- tests/test-path.lua
Error in normpath causes paths with leading '../../' to be removed.
Example:
normpath('../../a/b/c') == 'a/b/c'
Fix normpath to preserve leading '../../' in paths.
> Fix normpath

- lua/pl/xml.lua
- tests/test-xml.lua
Currently if you have an attribute name with an underscore, everything before the underscore is discarded during parsing.
```xml
<tag my_attribute='my_value'>Element contents</tag>
```
becomes
```xml
<tag attribute='my_value'>Element contents</tag>
```
This hopefully fixes this.
> xml attribute underscore fix for simle parser

- lua/pl/pretty.lua
- lua/pl/stringx.lua
- tests/test-pretty.lua
- tests/test-stringx.lua
Hey Steve,
I wanted to share this work with you, in case you found it useful. Please ignore/reject it if you don't find that it fits with Penlight's goals.
This pull request includes `stringx.quote_string` and changes to `pretty.write`. `quote_string` wraps a string such that reloading that string from a chunk of Lua code produces identical results:
```lua
mystr = "\n[[\n My tricky ]======] string.\n]]"
mystr2 = load("return " .. stringx.quote_string(mystr))()
assert(mystr == mystr2)
```
It provides the same facilities as `("%q"):format(str)`, plus:
* Uses long quotes when it finds a pattern that matches the long-quote pattern (begin or end, balance doesn't matter) or when it finds a `\n`.
* Adds an extra `\n` at the beginning, if found.
* When Long quotes are used, it always uses a …
> More Robust Quoted Strings

- lua/pl/xml.lua
This allows the user to specify a customized string for the XML prefacing. The function remains backwards compatible to existing users.
When specifying a string (instead of a boolean), the function will use that string instead of the default string. This allows to specify the encoding (e.g. UTF-8 and also beginning the string with BOM) and standalone etc. in the header.
> Allow XML tostring() function to customize the default prefacing with <?xml...>

- penlight-scm-1.rockspec
Fixes #137, obsoletes #96. The new scm-1 rockspec contains updated module list. There is no reason to keep old 1.1.0-3 rockspec, so I removed it. I'd recommend deleting old scm rockspecs from [luarocks](https://rocks.moonscript.org/modules/steved/penlight) and uploading this one instead, or it can be renamed to scm-3 and uploaded on top of old ones.
> Added up-to-date scm-1 rockspec

- lua/pl/stringx.lua
- tests/test-pylib.lua
- tests/test-stringx.lua
This PR fixes some tiny bugs, removes some unused things, adds some functionality for consistency (`last` argument for `lfind`, array of prefixes as argument for `startswith`), fixes documentation, adds tests, etc. See diffs and commit messages for details.
It seems there are some issues with various functions for splitting, and I'm not sure how to fix them as intended behaviour deviates from similar functions in Python's standard library. For instance, `stringx.splitlines` deliberately returns {""} when splitting an empty string ([link](https://github.com/stevedonovan/Penlight/blob/294522658bbc14ee6dc68938975c473f04b5dfd2/lua/pl/stringx.lua#L146)) which contradicts Python's docs: [2.7](https://docs.python.org/2/library/stdtypes.html#str.splitlines) …
> pl.stringx fixes

- lua/pl/tablex.lua
The documentation and code suggests that the comparison function, `cmp`, should be optional, but it currently crashes because of a call to `utils.function_arg` with `cmp = nil`.
> Make cmp argument optional in tablex.count_map

- lua/pl/Set.lua
New behavior: 
```lua 
stooges = Set{"moe","larry","curly"}
stooges = stooges + "shemp"
print(stooges) -- [moe,larry,curly,shemp]
capital = Set{"Constantinople"}
capital = capital + "Istanbul" - "Constantinople"
print(capital) -- Istanbul, not Constantinople now
```
This does not affect union and difference, which should be operations across Sets only imho.
> modifies + and - for Set class

- .travis.yml
Added a simple config for [Travis-Ci](https://travis-ci.org/) that runs tests under Lua 5.1-5.3 and LuaJIT 2.0 using their container infrastructure (no `sudo` used). You'll still have to log into travis-ci site and enable testing for this repo, but after that tests will be executed automatically for each push, [like this](https://travis-ci.org/mpeterv/Penlight/builds/79621620).
> Add travis-ci testing

- lua/pl/tablex.lua
The current implementation assumes that all the values are unique, and if they're not, it silently drops them. This implementation doesn't do that. Test with e.g. `tablex.sortv{a=1, b=2, c=1, d=2}`
> Fixed sortv

- lua/pl/template.lua
- tests/test-substitute.lua
Count expression nesting level when emitting code for a template, break up concatenations when it gets too large.
> Fix pl.template error for large templates

- .travis.yml
- tests/.luacov
- tests/tests.run
Added automated coverage gathering using luacov and luacov-coveralls. Similarly to Travis, you'll have to sign in to https://coveralls.io and enable it. It'll look like this: https://coveralls.io/github/mpeterv/Penlight
> Add coverage gathering

- lua/pl/lapp.lua
- tests/test-lapp.lua
When shifting arguments to get a value of an option, update variable holding current argument. Fixes #160 plus incorrect file name assigned to `<long_option>_name`, see two new test cases.
> Fix option name used instead of option value in lapp

- lua/pl/dir.lua
I've noticed my program always leaves a /tmp/lua_* file behind, and I've finally been able to trace it to a pl.file.copy i'm running. On my Linux system, this function executes a "cp" shell command though the local function execute_command in the dir module. This function creates a path.tmpname to store the output of the command in case of error, but this file is never deleted. This PR deletes it.
> pl.dir.execute_command: delete tmpfile after use

- lua/pl/OrderedMap.lua
- tests/test-set.lua
Use raw access to check if a key exists, so that keys naming OrderedMap methods are handled correctly.
> Fix error in OrderedMap.set when key is a method name

- CHANGES.md
- lua/pl/tablex.lua
- tests/test-tablex.lua
Previously, a call to tablex.pairmap would overwrite values if a value
was returned for a key that already had a value. Now, when a value is
returned for a key that already exists, we convert the key's value into
a table containing the original value and append the new value being
returned into that table.  Running test-tablex.lua passed after this
modification.
Here's the motivating use case that will make this clearer:
trial_ids = {"001","001","002","002"}
--I'd like a list of which trials have ids 1 and which trials have ids 2, so I tried
--calling tablex.index_map:
trial_nums_for_ids = tablex.index_map(trial_ids)
--but I got this output (which occurs because index_map calls tablex.pairmap,
--which overwrites the value associated with a key whenever a value is returned
--for an …
> tablex.pairmap: append if key already exists

- tests/test-executeex.lua
I was trying to find a local issue with executeex (it didn't capture stdout on Windows) by writing tests but I wasn't able to find it... so here are the tests I did anyway. If later I can reproduce the failing case I'll add it to these tests.
> Added tests for pl.utils.executeex()

- lua/pl/path.lua
> Fix path.relpath on Windows when switching drives.

- lua/pl/utils.lua
When Lua is compiled with MSVC14 (Visual Studio 2015), utils.executeex() always fails with “The filename, directory name, or volume label syntax is incorrect”. This is because on that C runtime library, os.tmpname() returns a full path (something like “C:\Users\Walther\AppData\Local\Temp\s290.2”) and the code that prepends the value of the TEMP environment variable in an attempt to deal with the output of older C runtime libraries (something like “\s558.2” on MSVC10, I didn’t try any others) creates an invalid path due to the ‘:’ in the duplicated drive letter.
Both cases are observed on the same Windows 7 system with Lua 5.2.3.
The attached commit detects the full path and skips the workaround, making the function work on both versions.
Probably related to #187 but I didn’t check in …
> utils.executeex() fails on Windows with MSVC14

- lua/pl/utils.lua
First, documentation says it should return a function; second,
attempting to serialize memoization table may result in an error:
on Lua 5.3 ipairs() uses __index metamethod which may not work
if the function doesn't take numbers as arguments.
Fixes pl.pretty.write(_G) crashing on Lua 5.3.
> Return a function from utils.memoize instead of a table

- lua/pl/path.lua
- tests/test-path.lua
Rewrite path.normpath to first split out path anchor (drive or UNC path start or '/', '//' or '\') and then iterate over parts of remaining relative path.
This fixes issues with normpath not working correctly (comparing to Python's os.path.normpath) in these cases:
* When a path part starts with '..':
* `os.path.normpath("A/..B") == "A/..B"`
* `pl.path.normpath("A/..B") == "B"`
* When a path starts with './':
* `os.path.normpath("./A") == "A"`
* `pl.path.normpath("./A") == "./A"`
* When a path ends with '/.':
* `os.path.normpath("A/.") == "A"`
* `pl.path.normpath("A/.") == "A/."`
* When a path ends with '/':
* `os.path.normpath("A/") == "A"`
* `pl.path.normpath("A/") == "A/"`
* When a path starts with '//':
* `os.path.normpath("//") == "//"`
* `pl.path.normpath("//") == "/"`
I wrote [this …
> Fix path.normpath

- lua/pl/pretty.lua
- tests/test-pretty.lua
* Improve precision: use %.17g for floats and %d for integers.
* Format infinities and NaN in platform-independent way.
* Add two tests.
* Fix pretty.number accidentally converting integer input to float on Lua 5.3.
> Fix number formatting in pl.pretty

- lua/pl/utils.lua
utils.readfile allows opening in binary mode; add this option to writefile, too.
> Add is_bin argument to utils.writefile

- lua/pl/utils.lua
Read errors typically occur when filename actually points to
a directory. Unlike io.open, file:read doesn't prepend filename to
error message, so that using assert(utils.readfile(...)) produces
an uninformative error in this case. Fix it by adding
the prefix manually.
> Add "filename: " prefix to read errors in utils.readfile

- lua/pl/text.lua
Today, when I tried to build documentation in "doc" folder of ldoc using ldoc itself, I found that error:
```
reading configuration from config.ld
/var/tmp/portage/dev-lua/ldoc-9999/work/all/ldoc-9999/ldoc.lua:840: internal LDoc error
/usr/share/lua/5.1/pl/text.lua:68: attempt to index a nil value
stack traceback:
/usr/share/lua/5.1/pl/text.lua:68: in function 'dedent'
...dev-lua/ldoc-9999/work/all/ldoc-9999/doc/../ldoc/doc.lua:627: in function 'finish'
...dev-lua/ldoc-9999/work/all/ldoc-9999/doc/../ldoc/doc.lua:237: in function 'finish'
...v-lua/ldoc-9999/work/all/ldoc-9999/doc/../ldoc/parse.lua:424: in function <...v-lua/ldoc-9999/work/all/ldoc-9999/doc/../ldoc/parse.lua:424>
[C]: in function 'xpcall'
...v-lua/ldoc-9999/work/all/ldoc-9999/doc/../ldoc/parse.lua:424: in function 'file' …
```
> Fix the case where "s" is empty string in dedent()

- lua/pl/dir.lua
- tests/test-dir.lua
* Anchor lua patterns produced from shell patterns at the beginning.
"abc" now does not match "b*".
* "*" now matches any number of characters including zero.
* Case-normalize shell patterns before matching.
* Consistently case-normalize file names before matching.
* Adjust docs.
* Add tests.
> Fix shell patterns in pl.dir

- lua/pl/app.lua
- lua/pl/dir.lua
- lua/pl/utils.lua
- tests/test-utils.lua
Add a function for quoting command arguments for os.execute
and other functions using it. It correctly handles all special
symbols.
Use it in a few places where Penlight executes command.
Add tests. I've also extensively tested the function randomly using this script: https://gist.github.com/mpeterv/132cae34b55ae65394a6fc8f847010a8
> Add utils.quote_arg

- lua/pl/Map.lua
- tests/test-class.lua
- tests/test-config.lua
- tests/test-func.lua
- tests/test-job-query.lua
- tests/test-map.lua
- tests/test-pretty-number.lua
- tests/test-relpath.lua
- tests/test-tzone.lua
- tests/test-vector.lua
This prevents issues with executing `lua run.lua tests`, which would not be able to find the `pl` module
> Fix calls to require to not modify the global environment

- tests/test-import_into.lua
Fixes the reduced coverage of #215.
> Call pl.import_into() twice during tests, to trigger more code paths

- lua/pl/Map.lua
- lua/pl/array2d.lua
- lua/pl/data.lua
- lua/pl/dir.lua
- lua/pl/seq.lua
- lua/pl/stringx.lua
- lua/pl/tablex.lua
- lua/pl/text.lua
Whenever Map, List, or Set is used as a metatable it's fetched using `require('pl.<class>')` instead of through `pl.utils.stdmt`, so that all methods are set up. Fixes #144.
> Import pl classes before attaching their metatable

- lua/pl/template.lua
This can be used to aid debugging, e.g. when the template resides in a actual file.
> pl.template: Support customising the chunk "filename" (default: TMP)

- lua/pl/utils.lua
A little change to fix an usage example of the `utils.string_lambda()` function (string shall be closed properly).
> Fix usage example of string_lambda().

- lua/pl/stringx.lua
- tests/test-stringx.lua
Make `stringx.splitlines` more compliant with its Python analogue:
* Recognize `"\r\n"` as a single line end.
* Return an empty list for an empty string.
* Implement `keep_ends` argument.
This is potentially a breaking change. We may want to create a separate branch for such changes and new features (named `dev`, for example) so that it's possible to make bugfix releases from `master` branch.
> Fix stringx.splitlines

- lua/pl/compat.lua
fix `utils.execute` to return proper results when LuaJIT is being used with 52 compatibility enabled.
OpenResty just switched in having this enabled by default in their latest release, hence causing troubles...
> fix os.execute

- lua/pl/dir.lua
In the function `dir.getallfiles(...)` I would rename the argument `pattern` into `shell_pattern`. At the first time I used this function I thought the argument would be a lua regex and I wondered why my code didn't work ( yes, I didn`t read the doc very well :smile: ). Thus it is more clear that the argument has to be a shell_regex and not a lua one...
> dir.lua: Rename arg "pattern" to "shell_pattern"

- lua/pl/pretty.lua
pretty.load errors out, if a C hook function is installed (Lua 5.1). Reason: debug.gethook() returns a string as first return value in this case.  Then debug.sethook complains about the first argument being a string not a function.
> Workaround for error in pretty.load with a C hook

- doc/manual/03-strings.md
- lua/pl/template.lua
- tests/test-template.lua
This splits the template function into a compile step and a render step. This allows reusing a previously compiled template by just rendering it again using another `env`.
Backward compatible. Minor caveat is that it introduces 2 local variables in the template, but chances of name collisions are very low.
* adds (basic) tests for the template module
* reduced the string concatenation. Only one concat call is left.
* fixed a non-functional example in the docs
Please check ldoc comments to be ok.
> split the templating engine in a compile and render step

- lua/pl/lapp.lua
Fix error "attempt to concatenate a nil value (local 'vtype')" by
checking making sure vtype is not nil.
I encountered this error when using `ldoc` which uses penlight to compile awesome WM. The error was as follows:
```
Scanning dependencies of target ldoc                                                                                                                                                                               
[ 97%] Generating API documentation                                                                                                                                                                                
lua: /usr/share/lua/5.3/pl/lapp.lua:317: attempt to concatenate a nil value (local 'vtype') …
```
> Fix error in 'pl.lapp.process_options_string'

- .travis.yml
- appveyor.yml
- lua/pl/compat.lua
- lua/pl/path.lua
- lua/pl/utils.lua
- tests/test-executeex.lua
This PR will make compatibility enhancements to `compat.execute`.
> change compat.execute to behave similarly on Lua 5.1 and Lua > 5.1.

- lua/pl/seq.lua
- tests/test-seq.lua
Basically as I understand it, what `seq.last` does is, given some sequence `n`:
- if `n` >= 2, return the next pair of items at indices `i` and `i - 1` down the stream.
- if `n` < 2, return `nil` down the stream.
aka, `seq.last` works like a 'sliding window' where the window width fits 2 items.
However, the current implementation returns `nil` for an empty sequence, *when chaining the operators together*. This results in a script error and stacktrace as described in issue #252. In other words, the behavior between a sequence with `1` element and `0` element is different.
This PR corrects that inconsistency.
> Fix for seq.last when given an empty sequence.

- lua/pl/template.lua
- tests/test-template.lua
if a value is not auto-coercable to a string by `table.concat` then
rendering the template would fail with a hard error being thrown,
breaking the safety promise.
Base on the added test (without the fix enabled)
```
luajit: lua/pl/template.lua:143: invalid value (table) at index 2 in table for 'concat'
stack traceback:
[C]: in function 'concat'
lua/pl/template.lua:143: in function 'render'
tests/test-template.lua:194: in main chunk
[C]: at 0x010eb0da2c
Running tests/test-template.lua failed with code 256
thijss-mbp:penlight thijs$
```
This fix will make sure that neither the compiler nor renderer will throw a Lua error, they will always return a result, or `nil + err`.
> fix(template) implement forced tostring

- lua/pl/stringx.lua
- tests/test-stringx.lua
Pattern backtracking can cause strip to become unbearably slow.
See http://stackstatus.net/post/147710624694/outage-postmortem-july-20-2016
The attached testcase in this commit demonstrates the problem.
Solution based on
https://github.com/leafo/lapis/commit/4a58f5c12582796b3c7e0ad784630fc6be56b92d
> Fix vulnerable pattern in pl.stringx.strip

- lua/pl/tablex.lua
- tests/test-tablex.lua
Make these functions support tables featuring cycles.
> Make tablex.deepcopy and tablex.deepcompare cycle-aware.

- CHANGELOG.md
- appveyor.yml
- lua/pl/compat.lua
- lua/pl/utils.lua
- run.lua
- tests/test-executeex.lua
- tests/test-utils.lua
includes a few small backwards compatible changes:
- `utils.quit`: exit message is no longer required, and closes the Lua state (on 5.2+).
- `utils.assert_arg` and `utils.assert_string`: now return the validated value
- `pl.compat`: now exports the `jit` and `jit52` flags
> increased test coverage and updated docs: compat + utils

- CHANGELOG.md
- lua/pl/app.lua
- lua/pl/dir.lua
- lua/pl/path.lua
- tests/test-dir.lua
- tests/test-path2.lua
Use normalizing only for matching. Use original casing when applying. This problem only existed on Windows. Impacted functions:
- `path.common_prefix`: no longer forces results to lowercase
- `path.relpath`: no longer forces results to lowercase
- `dir.copyfile`: no longer creates files in forced lowercase
- `dir.movefile`: no longer moves files as forced lowercase
- `dir.makepath`: no longer creates directories as forced lowercase
Also added additional tests covering the new (and some old) behaviour.
fixes #297
> fix(path) return original casing instead of normalized

- lua/pl/pretty.lua
Having consistent output makes it easier to use it for test purposes,
such as when dumping tables and comparing it to some expected output.
> Use consistent element order in pretty.write

- .travis.yml
- appveyor.yml
- tests/lua/mod52.lua
> fix(tests) fix tests failing on Lua 5.4

- lua/pl/pretty.lua
- tests/test-pretty.lua
Table keys ordering has been introduce with commit 9aecd3f. Unfortunately
a table sort is apply on all keys, but sort with default comparator is
unable to sort table containing different value types like boolean or table.
A solution is to introduce a custom comparator.
With it keys are now in the following order:
- ordered number
- symbols
- sorted strings
- unorder numbers
> pl.pretty: fix table write with symbol as key

- CHANGELOG.md
- lua/pl/pretty.lua
The call should be as short as possible to make it quick to use.
The idea is to create a call that is self contained (without
previous declared locals and require statements), such that we do
not accidentally leave references behind.
example:
```lua
require"pl.pretty" (...)
```
currently this would require:
```lua
print(require("pl.pretty").write({...}))
```
> feat(pretty) add a debug function to quickly dump some values

- .editorconfig
- .luacheckrc
- CHANGELOG.md
- lua/pl/dir.lua
- lua/pl/lexer.lua
- lua/pl/permute.lua
OpenResty coroutines break Lua paradigms and hence can break in regular Lua code. The code now tries to detect if the original version are available and then uses those.
Fixes #265
> fix Openresty coroutine usage

- CHANGELOG.md
- lua/pl/strict.lua
- tests/test-strict.lua
1. predefine "_PROMPT2" besides just "_PROMPT"
2. tostring the name before concatenating
also adds docs an examples
> fix(strict) minor fixes to strict module

- .travis.yml
- appveyor.yml
there is a workaround for the "bit32" library, see https://github.com/moteus/luacov-coveralls/issues/26
> chore(ci) add CI support for Lua 5.4

- CHANGELOG.md
- lua/pl/class.lua
- tests/test-class.lua
Addresses #288. My smoke test is
lua5.1 -e 'class = require("pl.class") class.A() function A:_init(x) print("A", x) end A(3) class.B(A) B(4) class.C(B) C(5) class.D(C) function D:_init(x) print("D", x) end D(6) class.E(D) E(7) class.F(E) function F:_init(x) print("F", x, "THEN") self:super(x) end F(8) class.G(F) G(9) class.H(G) function H:_init(x) print("H", x, "THEN") self:super(x) end H(10) class.I(H) I(11)'
Explanation:
Currently _init is exempted from "fat inheritance", and _init inheritance works by a strange workaround where the base class exactly one level up is checked for _init at constructor time. This appears to be done so that :super() can work properly, but it means that _init cannot be inherited from a grandparent.
This patch adds a _parent_with_init field to all relevant …
> Allow inheritance of _init from more than one level up

- .luacheckrc
- CHANGELOG.md
- lua/pl/compat.lua
- lua/pl/dir.lua
- lua/pl/lexer.lua
- lua/pl/permute.lua
> fix(compat) OpenResty implementation of coroutine.wrap

- .travis.yml
Related to but does not solve №348, see [my comment there](https://github.com/lunarmodules/Penlight/issues/348#issuecomment-699465521).
> chore(ci): Test run examples as well as the regression suite

- CHANGELOG.md
- lua/pl/dir.lua
I missed converting `dir.walk` on my previous PR, sorry about that! Thanks @Tieske for jumping in and making a conversion, but that approach doesn't work — I did not dissect your algorithm fully because it was definitely faster to redo it from scratch than to debug the existing one, but I noticed you were not not keeping track of a stack of pending tasks. Coroutine-based algorithms for iterators effectively exploit the call stack as a data structure; when converting them to non-coroutine-based, you need to keep that data structure elsewhere.
I have not tested this extensively, but it passes both the `tests` and `examples` suites. I hadn't noticed the `examples` suite at all when I submitted #344 — thanks @alerque for the ping about it.
Fixes #348.
> pl.dir: convert dir.walk from coroutines to iterators, take 2

- .github/workflows/luacheck.yml
- .luacheckrc
- .travis.yml
- README.md
- appveyor.yml
Luacheck isn't platform or Lua version dependant and doesn't need to run as part of every job. Having it in a separate workflow by itself will be simpler, faster, and also provide its status independently of other tests making it easier to review test failures.
> Break out linting into its own CI workflow

- penlight-dev-1.rockspec
- penlight-scm-3.rockspec
~~Only the last commit here is relevant, all the others are part of #355.~~
This is on hold until...
- ~~[ ] Immediately before a tagged release so the SCM rockspec rename doesn't cause issues between releases~~
> Tweak rockspec to normalize fields, callout spec version, etc.

- CHANGELOG.md
- lua/pl/permute.lua
- lua/pl/utils.lua
- spec/utils-deprecate_spec.lua
based on discussion here: https://github.com/lunarmodules/Penlight/issues/285#issuecomment-704970085
> Feat: Deprecate warnings

- .github/workflows/luacheck.yml
- CHANGELOG.md
- lua/pl/dir.lua
- tests/test-dir.lua
`rmtree` would fail when an entry somewhere in the tree was a symlink to another directory.
Links to files would be deleted, but links to directories would cause an error.
This PR ensures that symlinks to directories are also deleted in the same way.
Also adds tests.
> fix(dir.rmtree) remove symlinks without following

- CHANGELOG.md
- lua/pl/compat.lua
- lua/pl/permute.lua
- lua/pl/utils.lua
- spec/utils-deprecate_spec.lua
- tests/test-strict.lua
also updates the deprecation warnings to use the warn function.
some defaults to be validated (see TODO comments)
> feat(compat) add a 5.4 compatible "warn" function

- CHANGELOG.md
- lua/pl/pretty.lua
- tests/test-pretty.lua
Issue for Lua 5.3+ since that honours the metamethods when iterating.
fixes #257
> fix(pretty) do not fail on erroring metamethods

- CHANGELOG.md
- lua/pl/app.lua
- lua/pl/utils.lua
- tests/test-app.lua
- tests/test-utils.lua
> fix(app) parse values correctly, also update splitv

- CHANGELOG.md
- README.md
- lua/pl/dir.lua
- lua/pl/path.lua
also wraps LFS functions to provide more descriptive error messages
> fix(dir) makepath failed to create top-level directories

- tests/lua/mod52.lua
see http://lua-users.org/lists/lua-l/2021-04/msg00024.html
> fix tests on Lua 5.4.3

- CHANGELOG.md
- lua/pl/stringx.lua
- lua/pl/types.lua
- tests/test-stringx.lua
> fix(stringx) strip using wrong index if # > 200

- CHANGELOG.md
- lua/pl/path.lua
I'm using an alternative LuaFileSystem implementation that checks num of args. It now errors with pl 1.10 because `pl.path.currentdir` is calling `lfs.currentdir` with 1 argument, `nil`.
According to [LuaFileSystem Reference](https://keplerproject.github.io/luafilesystem/manual.html) `lfs.currentdir` does not accept any argument. This PR removes the argument in both `pl.path.currentdir` and the call to `lfs.currentdir`.
> fix(path) currentdir does not accept parameters

- CHANGELOG.md
- lua/pl/utils.lua
For library code you want a stacktrace attached to show from where the deprecated function was called. But for applications that is not the case, you simply want to inform the user a feature will be removed. No need to harass the user with stacktraces in that case.
> feat(deprecate) make stacktrace optional

- .luacheckrc
- CHANGELOG.md
- lua/pl/utils.lua
- spec/utils-npairs_spec.lua
Most importantly It honours the `table.n` size field by default. Similar to `utils.pack` and `utils.unpack`. This allows to iterate quickly over a table with "holes".
> feat(utils) add `npairs` nil-safe numeric iterator

- CHANGELOG.md
- lua/pl/text.lua
- spec/text_spec.lua
Previously it would detect the indent from the 1st line only, and just chop of text of the later lines.
Also adds two tests for indent/dedent regaring newlines added.
> fix(text) dedent now handles declining indents and empty lines

- CHANGELOG.md
- lua/pl/array2d.lua
For array2d: if the first index passed to default_range is a string and others are nil, parse_range(s) is used instead.
> feat(array2d) Automatically parse_range for string index

- CHANGELOG.md
- lua/pl/lapp.lua
- tests/test-lapp.lua
Currently lapp fails to parse enums that have advanced characters `-()` due to `string.match` treating them as pattern matching elements. Switch to using `string.find` with `plain=true`
> enable lapp to have advanced characters in enums

- CHANGELOG.md
- lua/pl/text.lua
- spec/text_spec.lua
`text.wrap` returns empty list for one-character strings, this PR fixes this by using `<=` instead of `<` for the iterator
> [fix] text.wrap now returns non-empty list for one character strings

- CHANGELOG.md
- lua/pl/import_into.lua
This seems like a typo; gmt.__index is always overridden below, so this currently would do nothing, and we wouldn't want to use another table's __newindex as this table's __index.
gmt does sometimes have its own __newindex set below, but AFAICT the case where it's set is mutually exclusive with this case. (__newindex is only set if mod is truthy; mod is truthy if env is originally true, in which case it is set to an empty table; prevenvmt is env's metatable, so not set in that case.)
> Fixes import_into using the previous environment's __newindex if set

- CHANGELOG.md
- lua/pl/compat.lua
> Make compat.warn compatible with OpenResty's global scope

- CHANGELOG.md
- lua/pl/utils.lua
- spec/utils-enum_spec.lua
- spec/utils-kpairs_spec.lua
adds:
- feature: `utils.enum` accept hash tables as well
- feature: `utils.kpairs` iterator over all non-integer keys (inverse of ipairs)
> update utils; enum + kpairs

- penlight-dev-1.rockspec
- rockspecs/penlight-1.10.0-2.rockspec
- rockspecs/penlight-1.11.0-2.rockspec
- rockspecs/penlight-1.12.0-2.rockspec
- rockspecs/penlight-1.6.0-2.rockspec
- rockspecs/penlight-1.7.0-2.rockspec
- rockspecs/penlight-1.8.0-2.rockspec
- rockspecs/penlight-1.8.1-2.rockspec
- rockspecs/penlight-1.9.1-2.rockspec
- rockspecs/penlight-1.9.2-2.rockspec
GitHub has completely blocked access to pull over insecure over-the-wire protocols including http:// and git://.
I'm not quite sure how to handle all the historical rockspecs. They could be left in a broken state or (as this currently does) we can fix them in place and just not worry about bumping the rockrel so that they are usable for direct testing (say from a CI job that loads old versions directly from the rockspecs).
> Update all rockspecs so they can actually still pull from GitHub

- .github/workflows/luacheck.yml
As of v0.26.0, the Luacheck repository is enabled to run *as* a GH
Action so there is no need to install Lua, LuaRocks, then the linter,
etc. Just one `uses:`.
This also removes Luarocks rockspec linter, but I think that belongs in
an altogether different place in the workflow(s).
> chore(ci) Utilize new upstream Luacheck Action

- CHANGELOG.md
- lua/pl/xml.lua
- tests/test-xml.lua
Penlight 1.12.0 has a bug where giving a file name to `xml.parse()` (with second argument `true`) will return nonsense (the file name again). It was broken in b749d88 due to a mistake in local variable scoping.
The attached commits add a test and fix the bug.
> fix(xml) fix xml.parse() with filename

- CHANGELOG.md
- lua/pl/pretty.lua
- tests/test-pretty.lua
Function defined when sorting table is not deterministic and makes luajit
crash with error:
prefix/share/lua/5.1/pl/pretty.lua:286: invalid order function for sorting
This patch will fix the problem #429
> fix(pretty) error in pl.pretty table sort function

- CHANGELOG.md
- lua/pl/lapp.lua
- tests/test-lapp.lua
Currently if the default value is used for a filename, the arg table will not be populated with `*_name`. Added a fix for this scenario.
The below snippet would currently not pass `f_name` in the arg table
```lua
lapp.process_options_string([[
-f    (file-out default test.txt)
]], {})
```
> fix(lapp) add file name to arg table when using the default value

- CHANGELOG.md
- lua/pl/lapp.lua
- tests/test-lapp.lua
Fix for #248. For now it follows lua variable name definition where the first letter cannot be a number.
> lapp support positional args with numbers

- CHANGELOG.md
- lua/pl/compat.lua
> fix(compat) use rawget to bypass "strict" checkers

- README.md
> Fix the link of LuaFileSystem

- CHANGELOG.md
- lua/pl/utils.lua
- spec/utils-choose_spec.lua
- tests/test-utils.lua
The original implementation of choose would fail if val1 was falsy. I have fixed this by replacing the "and/or" ternary logic with an if statement.
Example of failure:
choose(true, nil, "hello") -- returns "hello"
choose(true, false, "hello") -- returns "hello"
Internally, the evaluated expressions were as follows:
true and nil or "hello"  -- returns "hello"
true and false or "hello" -- returns "hello"
This commit updates the logic to be as follows:
if true then return nil else return "hello" end  -- returns nil
if true then return false else return "hello" end -- returns false
> fix(utils) nil values in choose(cond, val1, val2)

- CHANGELOG.md
- lua/pl/func.lua
- spec/func_spec.lua
Previously, func.compose only supported two functions, as in:
compose(print, string.upper)("hello") -- prints "HELLO"
This commit enables any number of functions to be composed by internally leveraging tablex.reduce to repeatedly apply functions.
For example:
compose(bind1(add, 10), bind1(mul, 5), bind(div, _1, 3))(9)
-- prints "25"
One can also pass functions as a table:
compose({ bind1(add, 10), bind1(mul, 5), bind(div, _1, 3) })(9)
-- prints "25"
> enhance(func) Extend compose to suport N functions

- lua/pl/pretty.lua
- tests/test-pretty.lua
> fix(pretty): update integer check for Lua5.4

- CHANGELOG.md
- CONTRIBUTING.md
- docs_topics/01-introduction.md
- docs_topics/02-arrays.md
- docs_topics/03-strings.md
- docs_topics/04-paths.md
- docs_topics/05-dates.md
- docs_topics/06-data.md
- docs_topics/07-functional.md
- docs_topics/08-additional.md
- lua/pl/List.lua
- lua/pl/app.lua
- lua/pl/array2d.lua
- lua/pl/class.lua
- lua/pl/config.lua
- lua/pl/data.lua
- lua/pl/func.lua
- lua/pl/import_into.lua
- lua/pl/init.lua
- lua/pl/permute.lua
- lua/pl/stringx.lua
- lua/pl/utils.lua
- lua/pl/xml.lua
- spec/array2d_spec.lua
- tests/test-app.lua
- tests/test-config.lua
- tests/test-func.lua
This PR fixes various typos I spotted in the documentation.
I tried to regenerate the docs using `ldoc` (version 1.4.6). However I realized that not only typos were changed, but also the format of some links, ... . Therefore, I'm leaving regeneration of docs up to you, feel free to push doc changes on my branch `fix-typos`.
> docs: Fix typos

- .github/workflows/luacheck.yml
- .github/workflows/unix_build.yml
This PR bumps GitHub action workflows to latest versions, thus avoiding deprecation warnings.
> Bump GitHub workflow actions to latest versions

- lua/pl/template.lua
- tests/test-template.lua
Closes https://github.com/lunarmodules/Penlight/issues/466.
> docs(template): Fix `newline` option description

- CHANGELOG.md
- lua/pl/path.lua
- spec/path_spec.lua
- tests/test-path.lua
see https://github.com/Kong/lua-resty-aws/issues/110
> fix(pl.path): make expanduser more sturdy

- CHANGELOG.md
- lua/pl/template.lua
- tests/test-template.lua
This PR tweaks the `template` module to build intermediate template code where instructions have the same line numbers as in the original template.
For example, with the old behaviour, the template
```
a $(foo + 1) b
```
would have resulted in the following intermediate code:
```lua
return function()
local __R_size, __R_table, __tostring = 0, {}, __tostring
local foo = 1
__R_size = __R_size + 1; __R_table[__R_size] = "a "
__R_size = __R_size + 1; __R_table[__R_size] = __tostring((foo + 1) or '')
__R_size = __R_size + 1; __R_table[__R_size] = " b\
"
bar()
return __R_table
end
```
If `bar()` were to produce an error, Lua would report it as occurring on line 8, which is completely unhelpful. However, after this PR, the above template will produce the following code:
```lua
return function() …
```
> enhance(template): Preserve line numbers

- lua/pl/Map.lua
The `keys`and `values` are improperly listed as fields instead of methods. There is no such a problem for `OrderedMap`.
The documentation for `items` explicitly mention the ordering for keys
> fix(docs): add 2 missing methods of Map.lua

- docs_topics/01-introduction.md
- docs_topics/02-arrays.md
- docs_topics/03-strings.md
- docs_topics/05-dates.md
- docs_topics/06-data.md
- docs_topics/08-additional.md
- lua/pl/path.lua
This is not ready to merge.
Some links were broken and have been fixed in files of the repo.
I could not build the documentation by myself with ldoc (error: unknown file attribute: b)
and I could not find a way to make `ldoc` replace "`lsf.dir`" in file
```
docs_topics/04-paths.md
```
by
```
<a href="https://lunarmodules.github.io/luafilesystem/manual.html#dir">lfs.dir</a>
```
in file
```
docs/manual/04-paths.md.html
```
instead of
```
<a href="http://stevedonovan.github.io/lua-stdlibs/lfs.html#dir">lfs.dir</a>
```
which is the broken link
> Documentation: fix lfs, stevedonovan and orbit broken links

- lua/pl/utils.lua
Document `utils.execute` function referred to in `quote_arg` documentation.
BEWARE: this is not tested because I cannot build locally the whole documentation.
> Document `utils.execute` in utils.lua

- lua/pl/path.lua
It is documented to return nil whereas it returns false
> docs(path): fix documentation of path.exists

- lua/pl/path.lua
Actually, `path.abspath(P,false)` is equivalent to `path.abspath(P)`. This PR raises on the former instruction.
> chore(path): validate path if given in abspath

- CHANGELOG.md
- lua/pl/types.lua
- tests/test-types.lua
if a metatable doesn't itself have a `__call` function, but gets one through another metatable, then the original object is NOT callable. Lua will query the metatable using `rawget`, and hence will not return the nested `__call` function
Reported by @tmillr [here](https://github.com/lunarmodules/luassert/issues/160#issuecomment-2351292281)
> fix(callable): __call cannot be in a nested metatable

- rockspecs/penlight-1.14.0-3.rockspec
The latest release on luarocks.org has a bug in the rockspec's `build.modules`, mapping `build.compat` to the `config` module.
```lua
["pl.config"] = "lua/pl/config.lua",
["pl.compat"] = "lua/pl/config.lua",
```
This PR proposes a new `-3` rockspec for the current release with a fix.
> fix(rockspec): compat module

- lua/pl/app.lua
- lua/pl/seq.lua
Here are some more Lua 5.5 loop constant fixes.
The tests now look the same for me with a local build of Lua 5.5 beta as
with Lua 5.{1..4}.
> fix(*): some more Lua 5.5 fixes for constant loop variables
